#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
				CREATE USER $APP_USER WITH PASSWORD '$APP_PASSWORD'; 
				CREATE DATABASE $APP_DB;
				GRANT ALL PRIVILEGES ON DATABASE $APP_DB TO $APP_USER;
				\connect $APP_DB $APP_USER
				BEGIN;
								CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
				COMMIT;
EOSQL
